version: '3.6'

# Define the services/containers to be run
services:

  product:
    image: sonerd/product-service
    build: product-service
    ports:
    - 8080:8080
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    # as you can see we are using the name of the mongo service as hostname
    - spring.data.mongodb.uri=mongodb://my-mongodb:27017/products
    networks:
    - microservice-sample_mongo_net
  # standard spring data property


networks:
  microservice-sample_mongo_net:
    external: true